# Default initial positions for robotics_arm's ros2_control fake system

initial_positions:
  gripper_base_joint: 1.57
  gripper_joint: 0.8
  joint_1: 1.57
  joint_2: 1.57
  joint_3: 1.57
  joint_4: 1.57